apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    component: api
  ports:
    - protocol: TCP
      port: {{ .Values.api.ports.port }}
      targetPort: {{ .Values.api.ports.targetPort }}
  type: ClusterIP
