apiVersion: v1
kind: Service
metadata:
  name: planedb-service
spec:
  selector:
    component: planeDb
  ports:
    - protocol: TCP
      port: {{ .Values.planeDb.ports.port }}
      targetPort: {{ .Values.planeDb.ports.port }}
  type: ClusterIP
