apiVersion: v1
kind: Service
metadata:
  name: planeminio-service
spec:
  selector:
    component: planeMinio
  ports:
    - protocol: TCP
      port: {{ .Values.planeMinio.ports.port }}
      targetPort: {{ .Values.planeMinio.ports.targetPort}}
  type: ClusterIP
