apiVersion: v1
kind: Service
metadata:
  name:  proxy-service
spec:
  selector:
    component: proxy
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.proxy.ports.port }}
      targetPort: {{ .Values.proxy.ports.targetPort }}
      nodePort: {{ .Values.proxy.ports.nodePort }}

