apiVersion: v1
kind: Service
metadata:
  name: space-service
spec:
  selector:
    component: space
  ports:
    - protocol: TCP
      port: {{ .Values.space.ports.port }}
      targetPort: {{ .Values.space.ports.targetPort }}
  type: ClusterIP
