apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    component: web
  ports:
    - protocol: TCP
      port: {{ .Values.web.ports.port }}
      targetPort: {{ .Values.web.ports.targetPort }}
  type: ClusterIP
