apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
      component: plane-db
  template:
    metadata:
      labels:
        app: dev
        component: plane-db
    spec:
      containers:
        - name: plane-db
          image: "{{ .Values.planeDb.image.repository }}"
          Command:
              - postgres
              - "-c"
              - "max_connections=1000"

          ports:
            - containerPort: {{ .Values.planeDb.ports.targetPort }}

          envFrom:
            - configMapRef:
                name: global-config-map  
    
          env:
            - name:  POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: PGUSER

            - name:  POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: PGDATABASE

            - name:  POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: global-config-map
                  key: PGPASSWORD

            - name:  PGDATA
              value: "/var/lib/postgresql/data"

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc         
    
