apiVersion: apps/v1
kind:  StatefulSet
metadata:
  name: redis-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
      component: planeRedis
  template:
    metadata:
      labels:
        app: dev
        component: planeRedis
    spec:
      containers:
        - name: plane-redis
          image: "{{ .Values.planeRedis.image.repository }}"
          ports:
            - containerPort: {{ .Values.planeRedis.ports.targetPort }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
              
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc 